# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('idPlatillo', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id Platillo')),
                ('idProducto', models.BigIntegerField(blank=True, db_column='idProducto', verbose_name='Id Producto')),
                ('cantidadUtilizada', models.BigIntegerField(blank=True, db_column='cantidadUtilizada', verbose_name='Cantidad')),
                ('idIngrediente', models.BigIntegerField(blank=True, db_column='idIngrediente', verbose_name='Id Ingrediente')),
            ],
            options={
                'db_table': 'ingredientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idProducto', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadDeProducto', models.BigIntegerField(blank=True, db_column='cantidadDeProducto', verbose_name='Cantidad')),
                ('nombreDelProducto', models.CharField(blank=True, db_column='nombreDelProducto', max_length=255, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'invetario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('cliente', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Cliente')),
                ('nit', models.BigIntegerField(blank=True, db_column='nit', verbose_name='Nit')),
                ('idPlatillo', models.BigIntegerField(blank=True, db_column='idPlatillo', verbose_name='Id Platillo')),
                ('idMesero', models.BigIntegerField(blank=True, db_column='idMesero', verbose_name='Id Mesero')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
