# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, db_column='Cantidad', verbose_name='cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDelProducto', models.CharField(blank=True, db_column='nombreDelProducto', max_length=255, verbose_name='Nombre')),
                ('cantidadDeProducto', models.IntegerField(blank=True, db_column='cantidadDeProducto', verbose_name='Cantidad')),
                ('seccion', models.CharField(blank=True, db_column='Seccion', max_length=255, verbose_name='Seccion')),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDelMesero', models.CharField(db_column='NombreDelMesero', max_length=255, verbose_name='nombreDelMesero')),
                ('mesa', models.IntegerField(blank=True, db_column='Mesa', verbose_name='mesa')),
                ('fecha', models.DateTimeField(db_column='Fecha', max_length=255, verbose_name='fecha')),
                ('status', models.IntegerField(db_column='Estado', default=0, verbose_name='Estado')),
            ],
            options={
                'db_table': 'ordenes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDelPlatillo', models.CharField(db_column='NombreDelPlatillo', max_length=255, verbose_name='Nombre')),
                ('precioPlatillo', models.FloatField(blank=True, db_column='PrecioDelPlatillo', verbose_name='precio')),
                ('imagenPlatillo', models.CharField(db_column='ImagenPlatillo', max_length=255, verbose_name='Imagen')),
                ('descripcionPlatillo', models.CharField(blank=True, db_column='DescripcionDelPlatillo', max_length=255, verbose_name='Descripcion')),
                ('ingredientes', models.ManyToManyField(through='appcasona.Cantidad', to='appcasona.Inventario')),
            ],
            options={
                'db_table': 'platillo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='platillos',
            field=models.ManyToManyField(to='appcasona.Platillo'),
        ),
        migrations.AddField(
            model_name='cantidad',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcasona.Inventario'),
        ),
        migrations.AddField(
            model_name='cantidad',
            name='platillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcasona.Platillo'),
        ),
    ]
