# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcasona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='inventario',
            name='proveedor',
            field=models.ManyToManyField(to='appcasona.Proveedor'),
        ),
        migrations.RemoveField(
            model_name='platillo',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='platillo',
            name='ingredientes',
            field=models.ManyToManyField(to='appcasona.Inventario'),
        ),
    ]
