# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcasona', '0002_auto_20160828_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='descripcionPlatillo',
            field=models.CharField(blank=True, db_column='DescripcionDelPlatillo', max_length=255, verbose_name='Descripcion'),
        ),
    ]
