# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcasona', '0003_auto_20160818_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidadDeProducto',
            field=models.BigIntegerField(blank=True, db_column='cantidadDeProducto', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombreDelProducto',
            field=models.CharField(blank=True, db_column='nombreDelProducto', max_length=255, verbose_name='Nombre'),
        ),
    ]
