# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcasona', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='disponible',
        ),
    ]
