# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcasona', '0005_remove_platillo_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porciones',
            fields=[
                ('idPorciones', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadDeIngredientes', models.BigIntegerField(blank=True, db_column='cantidadDeIngredientes', verbose_name='Cantidad de Ingredientes')),
                ('ingredientes', models.ManyToManyField(to='appcasona.Inventario')),
            ],
            options={
                'db_table': 'porciones',
                'managed': True,
            },
        ),
    ]
