# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcasona', '0006_porciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='porciones',
            name='nombreDelPlatillo',
            field=models.ManyToManyField(to='appcasona.Platillo'),
        ),
    ]
