# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcasona', '0007_porciones_nombredelplatillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porciones',
            name='cantidadDeIngredientes',
            field=models.BigIntegerField(blank=True, db_column='cantidadDeIngrediente', verbose_name='Cantidad de Ingrediente'),
        ),
        migrations.RemoveField(
            model_name='porciones',
            name='nombreDelPlatillo',
        ),
        migrations.AddField(
            model_name='porciones',
            name='nombreDelPlatillo',
            field=models.CharField(db_column='NombreDelPlatillo', default=2, max_length=255, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
