# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcasona', '0008_auto_20161003_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porciones',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='porciones',
            name='ingredientes',
            field=models.CharField(db_column='NombreDelIngrediente', default=2, max_length=255, verbose_name='Ingrediente'),
            preserve_default=False,
        ),
    ]
